"use client";

// import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { Moderustic } from "next/font/google";
import { ModalProvider } from "@/components/ModalContext";
import StoreProvider from "@/providers/StoreProviders";

const moderustic = Moderustic({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "700"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={moderustic.className} lang="en">
      <body>
        <StoreProvider>
          <ModalProvider>
            <Header />
            {children}
            <Footer />
          </ModalProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
